// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// The CLI (migrate/db seed/studio) uses DIRECT_URL to avoid running DDL through
// a connection pooler (e.g. Neon's pgbouncer-style pooler). The running app uses
// the pooled DATABASE_URL directly via the adapter in src/lib/prisma.ts instead -
// Prisma 7's config `datasource` block has no `directUrl` field, only `url`.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
